version: "3"

interval: 100ms

# Include child Taskfiles
includes:
  timsseek: ./rust/timsseek

tasks:
  license_check:
    cmds:
      - cargo deny check

  test:
    cmds:
      - cargo test -- --nocapture
      - uv run python -m pytest

  fmt:
    cmds:
      - cargo +nightly fmt --verbose
      - uv run ruff format

  clippy:
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged {{.CLI_ARGS}} -- -D warnings

  todos:
    cmds:
      - grep -nH -R TODO rust/tims*/src
      - grep -nH -R "todo!" rust/tims*/src

  build_python:
    cmds:
      - uv build --all-packages --verbose

  bumpver:
    cmds:
      # --tag {alpha, beta, dev, rc, post, final}
      - uv run --dev  bumpver update --minor --allow-dirty --no-commit

  docker:
    cmds:
      # - cargo install cross --git https://github.com/cross-rs/cross
      - cross build --release --target x86_64-unknown-linux-gnu --bin timsquery_cli
      - cross build --release --target x86_64-unknown-linux-gnu --bin timsseek
      - docker build --platform linux/amd64 -t timsseek:local .

