version: "3"

interval: 100ms

# Include child Taskfiles
includes:
  timsquery: ./rust/timsquery
  timsseek: ./rust/timsseek

tasks:
  license_check:
    cmds:
      - cargo deny check

  test:
    cmds:
      - cargo test

  fmt:
    cmds:
      - cargo +nightly fmt --verbose
      - uv run ruff format

  clippy:
    cmds:
      - cargo clippy {{.CLI_ARGS}}

  bench:
    cmds:
      - task: timsquery:bench

  todos:
    cmds:
      - grep -nH -R TODO rust/tims*/src
      - grep -nH -R "todo!" rust/tims*/src

  build_python:
    cmds:
      - uv build --all-packages --verbose

  bumpver:
    cmds:
      - uv run --dev  bumpver update --minor --allow-dirty --no-commit
