//! Per-ion m/z and mobility error arrays. Array family: each `[f32; N]` field
//! fans out to one feature per ion, and the `#[feat(..)]` list adds the
//! linear-model companions — `abs` (magnitude, since these errors are
//! center-is-better) and `isna` (missing ion / mobility dim, not-missing-at-
//! random). `columns` emits only the raw signed arrays.
//!
//! Changing an ion count means editing `NUM_MS*_IONS`; the array lengths and
//! all `{field}_{i}` names flow from there. Column/feature names are `{field}_
//! {i}` (+ transform suffix), generated by the macro — no name table.

use crate::score_block;
use crate::scoring::offsets::MzMobilityOffsets;
use crate::scoring::{
    NUM_MS1_IONS,
    NUM_MS2_IONS,
};

score_block! {
    /// Stage: finalize (per-ion m/z and mobility errors from the apex offsets).
    pub struct IonErrors {
        #[feat(raw, abs, isna)] pub ms2_mz_errors: [f32; NUM_MS2_IONS],
        #[feat(raw, abs, isna)] pub ms2_mobility_errors: [f32; NUM_MS2_IONS],
        #[feat(raw, abs, isna)] pub ms1_mz_errors: [f32; NUM_MS1_IONS],
        #[feat(raw, abs, isna)] pub ms1_mobility_errors: [f32; NUM_MS1_IONS],
    }
}

impl IonErrors {
    pub fn compute(offsets: &MzMobilityOffsets) -> Self {
        Self {
            ms2_mz_errors: offsets.ms2_mz_errors(),
            ms2_mobility_errors: offsets.ms2_mobility_errors(),
            ms1_mz_errors: offsets.ms1_mz_errors(),
            ms1_mobility_errors: offsets.ms1_mobility_errors(),
        }
    }

    pub fn neutralize(&mut self) {
        self.ms1_mobility_errors.fill(f32::NAN);
        self.ms2_mobility_errors.fill(f32::NAN);
    }
}
