//! Score blocks: modular, macro-generated scoring fields.
//!
//! A *score* belongs to a *family*; a family is one file that owns its whole
//! lifecycle — compute-from-inputs, parquet projection (`columns`), and the two
//! ML projections (`features` = values, `feature_names` = names). Adding a score
//! to an existing family touches only that file, and forgetting a projection is
//! structurally impossible: all three bodies are generated by walking the same
//! field list that defines the struct (see [`crate::score_block!`]), so a
//! partial emission is unrepresentable. Feature *values* are per-record
//! ([`FeatSink`]); feature *names* are a property of the set, built once
//! ([`NameSink`]). The heavy apex-stage families ([`apex_features`],
//! [`split_product`]) keep their compute here too, leaning on the shared numeric
//! primitives in `crate::scoring::apex_dsp`.
//!
//! [`crate::score_block!`] handles both scalar and array (`[f32; N]`) fields,
//! so the array families [`ion_errors::IonErrors`] /
//! [`relative_intensities::RelativeIntensities`] are macro-generated too (names
//! `{field}_{i}` from the field + count). Hand-written exceptions that still
//! emit through the same sinks, with compute in-file:
//! - [`identity::Identity`] — irreducibly mixed-dtype.
//! - the conditional, features-only [`sequence_counts`] block.
//!
//! The remaining blocks — including the output-only
//! [`result_meta::ResultMeta`] — are macro-generated by [`crate::score_block!`].

use arrow::array::*;
use arrow::datatypes::*;
use std::sync::Arc;

pub mod apex_features;
pub mod counts;
pub mod derived;
pub mod frame;
pub mod identity;
pub mod intensities;
pub mod ion_errors;
pub mod lazy;
pub mod mobility;
pub mod primary;
pub mod relative_intensities;
pub mod result_meta;
pub mod rt;
pub mod sequence_counts;
pub mod split_product;

pub use frame::{
    FeatFrame,
    FrameSink,
};

// ---------------------------------------------------------------------------
// Trait
// ---------------------------------------------------------------------------

/// A family of scores that projects itself into the two output surfaces.
///
/// `columns` emits the raw stored value at its original dtype (the Parquet
/// projection). Array fields fan out to one column per element, named
/// `{field}_{i}`. `features` emits the ML projection, which may apply
/// `#[feat(..)]` transforms and fan a single field out to several features.
pub trait ScoreBlock {
    fn columns(&self, out: &mut ColSink);
    /// Emit this block's ML feature *values*, in a fixed per-block order.
    fn features(&self, out: &mut FeatSink);
    /// Emit this block's ML feature *names*, in the same order as
    /// [`ScoreBlock::features`]. Associated (no `&self`): names are a property
    /// of the feature set, built once, not carried per record. For macro blocks
    /// both walks are generated from the one field list, so they cannot desync.
    fn feature_names(out: &mut NameSink);
}

// ---------------------------------------------------------------------------
// ColSink — row-oriented Parquet column accumulator
// ---------------------------------------------------------------------------

enum ColData {
    F32(Vec<f32>),
    F64(Vec<f64>),
    U8(Vec<u8>),
    U32(Vec<u32>),
    Bool(Vec<bool>),
    Str(Vec<String>),
}

struct Column {
    name: String,
    nullable: bool,
    data: ColData,
}

/// Accumulates Parquet columns one row at a time.
///
/// Each block's `columns(&self, o)` pushes one value per column, in a fixed
/// order per block. On the first row the columns are created (name + dtype +
/// nullability recorded from the typed method); on later rows the cursor walks
/// the existing columns and appends. Scalars are non-nullable; expanded array
/// columns (`f32_array`) are nullable — this preserves the pre-block
/// column name→dtype→nullability set.
#[derive(Default)]
pub struct ColSink {
    cols: Vec<Column>,
    cursor: usize,
}

impl ColSink {
    pub fn new() -> Self {
        Self::default()
    }

    /// Locate the column at the cursor (creating it with an empty `make()`
    /// buffer on the first row), advance the cursor, and hand back its data
    /// buffer for the caller to append one value to. Centralizes the
    /// first-row-vs-append + order-check logic shared by every typed method.
    fn slot(&mut self, name: &str, nullable: bool, make: impl FnOnce() -> ColData) -> &mut ColData {
        let i = self.cursor;
        if i == self.cols.len() {
            self.cols.push(Column {
                name: name.to_string(),
                nullable,
                data: make(),
            });
        } else {
            debug_assert_eq!(self.cols[i].name, name, "column order mismatch");
        }
        self.cursor += 1;
        &mut self.cols[i].data
    }

    fn push_f32(&mut self, name: &str, nullable: bool, v: f32) {
        match self.slot(name, nullable, || ColData::F32(Vec::new())) {
            ColData::F32(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn f32(&mut self, name: &str, v: f32) {
        self.push_f32(name, false, v);
    }

    pub fn f64(&mut self, name: &str, v: f64) {
        match self.slot(name, false, || ColData::F64(Vec::new())) {
            ColData::F64(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn u8(&mut self, name: &str, v: u8) {
        match self.slot(name, false, || ColData::U8(Vec::new())) {
            ColData::U8(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn u32(&mut self, name: &str, v: u32) {
        match self.slot(name, false, || ColData::U32(Vec::new())) {
            ColData::U32(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn bool(&mut self, name: &str, v: bool) {
        match self.slot(name, false, || ColData::Bool(Vec::new())) {
            ColData::Bool(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn str(&mut self, name: &str, v: &str) {
        match self.slot(name, false, || ColData::Str(Vec::new())) {
            ColData::Str(vals) => vals.push(v.to_string()),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    /// Expand a fixed-size `[f32; N]` into `{prefix}_0 .. {prefix}_{N-1}`
    /// nullable columns (matching the pre-block array-column layout).
    pub fn f32_array<const N: usize>(&mut self, prefix: &str, arr: &[f32; N]) {
        for (i, v) in arr.iter().enumerate() {
            self.push_f32(&format!("{prefix}_{i}"), true, *v);
        }
    }

    /// Finish one row: reset the cursor to the first column.
    pub fn end_row(&mut self) {
        self.cursor = 0;
    }

    /// Drop all accumulated row data, keeping the established schema. Used to
    /// produce a zero-row batch (schema only) from a single sample row.
    pub fn clear_rows(&mut self) {
        for c in &mut self.cols {
            match &mut c.data {
                ColData::F32(v) => v.clear(),
                ColData::F64(v) => v.clear(),
                ColData::U8(v) => v.clear(),
                ColData::U32(v) => v.clear(),
                ColData::Bool(v) => v.clear(),
                ColData::Str(v) => v.clear(),
            }
        }
        self.cursor = 0;
    }

    /// Materialize the accumulated columns into arrow fields + arrays.
    pub fn finish(self) -> (Vec<Field>, Vec<Arc<dyn Array>>) {
        let mut fields = Vec::with_capacity(self.cols.len());
        let mut arrays: Vec<Arc<dyn Array>> = Vec::with_capacity(self.cols.len());
        for c in self.cols {
            let (dtype, arr): (DataType, Arc<dyn Array>) = match c.data {
                ColData::F32(v) => (DataType::Float32, Arc::new(Float32Array::from(v))),
                ColData::F64(v) => (DataType::Float64, Arc::new(Float64Array::from(v))),
                ColData::U8(v) => (DataType::UInt8, Arc::new(UInt8Array::from(v))),
                ColData::U32(v) => (DataType::UInt32, Arc::new(UInt32Array::from(v))),
                ColData::Bool(v) => (DataType::Boolean, Arc::new(BooleanArray::from(v))),
                ColData::Str(v) => (
                    DataType::Utf8,
                    Arc::new(StringArray::from_iter(v.into_iter().map(Some))),
                ),
            };
            fields.push(Field::new(c.name, dtype, c.nullable));
            arrays.push(arr);
        }
        (fields, arrays)
    }
}

// ---------------------------------------------------------------------------
// FeatSink — ML feature accumulator
// ---------------------------------------------------------------------------

/// Accumulates ML feature *values* in emission order. Names are not stored here
/// — they are a property of the set, built once by [`NameSink`]. The
/// transform-suffix convention (`_ln1p`, `_round`, …) is fixed and lives only in
/// the `#[feat(..)]` grammar; the value transforms live here so a value and its
/// name-suffix are defined by the same directive.
#[derive(Default)]
pub struct FeatSink {
    vals: Vec<f64>,
}

impl FeatSink {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, v: f64) {
        self.vals.push(v);
    }

    /// Push one raw value per array element (`f32` widened to `f64`). Shared by
    /// the array blocks ([`ion_errors`], [`relative_intensities`]).
    pub fn push_slice(&mut self, vals: &[f32]) {
        self.vals.extend(vals.iter().map(|v| *v as f64));
    }

    pub fn push_ln1p(&mut self, x: f64) {
        self.vals.push(x.ln_1p());
    }

    pub fn push_round(&mut self, x: f64) {
        self.vals.push(x.round());
    }

    /// Magnitude fold (`|x|`, NaN preserved). Turns a center-is-better signed
    /// feature (small error good, both tails bad) into a monotone one a linear
    /// discriminant can weight; inert for trees (monotone of the raw value).
    pub fn push_abs(&mut self, x: f64) {
        self.vals.push(x.abs());
    }

    /// Missingness indicator (`1.0` if the source value is non-finite, else
    /// `0.0`). Pairs with a value transform to encode not-missing-at-random
    /// structure a mean-impute would erase; the value column self-imputes to
    /// the mean model-side, this preserves the "was missing" bit.
    pub fn push_isna(&mut self, x: f64) {
        self.vals.push(if x.is_finite() { 0.0 } else { 1.0 });
    }

    /// `push_abs` for each element of an array field.
    pub fn push_slice_abs(&mut self, vals: &[f32]) {
        self.vals.extend(vals.iter().map(|v| (*v as f64).abs()));
    }

    /// `push_isna` for each element of an array field.
    pub fn push_slice_isna(&mut self, vals: &[f32]) {
        self.vals
            .extend(vals.iter().map(|v| if v.is_finite() { 0.0 } else { 1.0 }));
    }

    /// The accumulated values, in emission order.
    pub fn into_values(self) -> Vec<f64> {
        self.vals
    }
}

// ---------------------------------------------------------------------------
// NameSink — set-level ML feature-name accumulator
// ---------------------------------------------------------------------------

/// Builds the ML feature-name list ONCE for a whole fit (a property of the
/// feature set, not of any record). Names are `Arc<str>` so array families can
/// generate them lazily ([`NameSink::push_indexed`]) instead of const tables,
/// and so callers can share the list cheaply.
#[derive(Default)]
pub struct NameSink {
    names: Vec<Arc<str>>,
}

impl NameSink {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, name: &str) {
        self.names.push(Arc::from(name));
    }

    /// The array-family fan-out: `{prefix}_0 .. {prefix}_{n-1}` (mirrors
    /// [`ColSink::f32_array`]'s column naming).
    pub fn push_indexed(&mut self, prefix: &str, n: usize) {
        for i in 0..n {
            self.names.push(Arc::from(format!("{prefix}_{i}")));
        }
    }

    /// [`NameSink::push_indexed`] with a trailing transform suffix, so an
    /// array family's `abs`/`isna` companions read `{prefix}_{i}_abs` — the
    /// same `{name}{suffix}` convention the scalar macro uses.
    pub fn push_indexed_suffixed(&mut self, prefix: &str, n: usize, suffix: &str) {
        for i in 0..n {
            self.names.push(Arc::from(format!("{prefix}_{i}{suffix}")));
        }
    }

    /// The accumulated names, in emission order.
    pub fn into_names(self) -> Vec<Arc<str>> {
        self.names
    }
}

// ---------------------------------------------------------------------------
// BlockFixture — fixed sample constants for macro-generated `sample()`
// ---------------------------------------------------------------------------

/// Supplies a fixed constant per field type for a block's generated `sample()`.
/// Sample *values* are arbitrary but finite and non-zero (so ratio-derived
/// features stay finite in tests).
pub trait BlockFixture {
    fn fixture() -> Self;
}

impl BlockFixture for f32 {
    fn fixture() -> Self {
        0.5
    }
}
impl BlockFixture for f64 {
    fn fixture() -> Self {
        0.5
    }
}
impl BlockFixture for u8 {
    fn fixture() -> Self {
        1
    }
}
impl BlockFixture for u32 {
    fn fixture() -> Self {
        1
    }
}
impl BlockFixture for bool {
    fn fixture() -> Self {
        true
    }
}
impl<const N: usize> BlockFixture for [f32; N] {
    fn fixture() -> Self {
        [0.5; N]
    }
}

// ---------------------------------------------------------------------------
// score_block! — the block macro
// ---------------------------------------------------------------------------

/// Generate a score block: the struct, its [`ScoreBlock`] impl (`columns` +
/// `features` + `feature_names`), and a `sample()` fixture.
///
/// Scalar fields (`f32`/`f64`/`u8`/`u32`/`bool`/`str`) emit one column/feature;
/// array fields (`[f32; N]`) fan out to `{field}_{i}` per element. The three
/// projections all walk the one field list, so column values, feature values,
/// and feature names cannot desync.
///
/// Column and feature names are codegen (no golden pins them), so a rename here
/// just flows through to every surface.
///
/// It does NOT generate `compute` — that stays a hand-written inherent fn,
/// because dep signatures vary per block.
///
/// Every field carries exactly one directive attribute controlling its ML
/// (`features`) projection; `columns` always emits the raw value:
/// - `#[feat(t1, t2, ..)]` — one feature per transform (comma = fan-out).
///   Vocabulary: `raw` (no suffix), `ln1p` (`_ln1p`), `round` (`_round`),
///   `abs` (`_abs`, magnitude fold for linear models), `isna` (`_isna`,
///   non-finite indicator). Every transform is a pure per-row function; any
///   data-dependent step (standardize, inverse-normal) lives in the model.
/// - `#[raw]` — shorthand for `#[feat(raw)]`.
/// - `#[col_only]` — Parquet column only, no ML feature.
///
/// (The nested-compose grammar and the per-field `feat_with` escape hatch from
/// the design are deferred — unused by the current feature set.)
#[macro_export]
macro_rules! score_block {
    (
        $(#[doc = $doc:literal])*
        pub struct $Name:ident {
            $( #[$($d:tt)*] pub $fname:ident : $fty:tt ),* $(,)?
        }
    ) => {
        $(#[doc = $doc])*
        #[derive(Debug, Clone, Copy, ::serde::Serialize)]
        pub struct $Name {
            $( pub $fname : $fty ),*
        }

        impl $Name {
            /// Fixture with every field a fixed constant (see
            /// [`crate::scoring::blocks::BlockFixture`]).
            pub fn sample() -> Self {
                Self {
                    $( $fname : <$fty as $crate::scoring::blocks::BlockFixture>::fixture() ),*
                }
            }
        }

        impl $crate::scoring::blocks::ScoreBlock for $Name {
            fn columns(&self, o: &mut $crate::scoring::blocks::ColSink) {
                $( $crate::__block_col!(o, self, $fname, $fty); )*
            }
            fn features(&self, o: &mut $crate::scoring::blocks::FeatSink) {
                $( $crate::__block_feat!(o, self, $fname, $fty, $($d)*); )*
            }
            fn feature_names(o: &mut $crate::scoring::blocks::NameSink) {
                $( $crate::__block_feat_name!(o, $fname, $fty, $($d)*); )*
            }
        }
    };
}

/// Column emission dispatched by field type.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_col {
    ($o:ident, $s:ident, $f:ident, f32) => {
        $o.f32(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, f64) => {
        $o.f64(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, u8) => {
        $o.u8(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, u32) => {
        $o.u32(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, bool) => {
        $o.bool(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, str) => {
        $o.str(stringify!($f), &$s.$f);
    };
    // Array family: one `{field}_{i}` column per element (nullable), raw only.
    ($o:ident, $s:ident, $f:ident, [f32; $n:expr]) => {
        $o.f32_array(stringify!($f), &$s.$f);
    };
}

/// Feature *value* emission dispatched by the field's directive. Carries the
/// field type so the per-transform emit can dispatch scalar vs array.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat {
    ($o:ident, $s:ident, $f:ident, $fty:tt, col_only) => {};
    ($o:ident, $s:ident, $f:ident, $fty:tt, raw) => {
        $crate::__block_feat_one!($o, $s, $f, $fty, raw);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, feat($($t:ident),+ $(,)?)) => {
        $( $crate::__block_feat_one!($o, $s, $f, $fty, $t); )+
    };
}

/// A single transform's *value* in a `#[feat(..)]` list. Array-typed fields
/// (`[f32; N]`) fan out element-wise (`push_slice*`); every scalar type casts
/// to `f64` uniformly. Array arms are matched first; the `$fty:tt` scalar arms
/// are the fallthrough.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat_one {
    ($o:ident, $s:ident, $f:ident, [f32; $n:expr], raw) => {
        $o.push_slice(&$s.$f);
    };
    ($o:ident, $s:ident, $f:ident, [f32; $n:expr], abs) => {
        $o.push_slice_abs(&$s.$f);
    };
    ($o:ident, $s:ident, $f:ident, [f32; $n:expr], isna) => {
        $o.push_slice_isna(&$s.$f);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, raw) => {
        $o.push($s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, ln1p) => {
        $o.push_ln1p($s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, round) => {
        $o.push_round($s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, abs) => {
        $o.push_abs($s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, $fty:tt, isna) => {
        $o.push_isna($s.$f as f64);
    };
}

/// Feature *name* emission dispatched by the field's directive. Mirrors
/// [`__block_feat`] one-for-one so value and name order cannot diverge.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat_name {
    ($o:ident, $f:ident, $fty:tt, col_only) => {};
    ($o:ident, $f:ident, $fty:tt, raw) => {
        $crate::__block_feat_name_one!($o, $f, $fty, raw);
    };
    ($o:ident, $f:ident, $fty:tt, feat($($t:ident),+ $(,)?)) => {
        $( $crate::__block_feat_name_one!($o, $f, $fty, $t); )+
    };
}

/// A single transform's *name* in a `#[feat(..)]` list. Array fields fan out to
/// `{field}_{i}` (+ transform suffix); scalars to `{field}` (+ suffix).
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat_name_one {
    ($o:ident, $f:ident, [f32; $n:expr], raw) => {
        $o.push_indexed(stringify!($f), $n);
    };
    ($o:ident, $f:ident, [f32; $n:expr], abs) => {
        $o.push_indexed_suffixed(stringify!($f), $n, "_abs");
    };
    ($o:ident, $f:ident, [f32; $n:expr], isna) => {
        $o.push_indexed_suffixed(stringify!($f), $n, "_isna");
    };
    ($o:ident, $f:ident, $fty:tt, raw) => {
        $o.push(stringify!($f));
    };
    ($o:ident, $f:ident, $fty:tt, ln1p) => {
        $o.push(concat!(stringify!($f), "_ln1p"));
    };
    ($o:ident, $f:ident, $fty:tt, round) => {
        $o.push(concat!(stringify!($f), "_round"));
    };
    ($o:ident, $f:ident, $fty:tt, abs) => {
        $o.push(concat!(stringify!($f), "_abs"));
    };
    ($o:ident, $f:ident, $fty:tt, isna) => {
        $o.push(concat!(stringify!($f), "_isna"));
    };
}
