//! Score blocks: modular, macro-generated scoring fields.
//!
//! A *score* belongs to a *family*; a family is one file that owns its whole
//! lifecycle — compute-from-inputs, parquet projection (`columns`), and ML
//! projection (`features`). Adding a score to an existing family touches only
//! that file, and forgetting the ML projection is structurally impossible: the
//! `columns`/`features` bodies are generated by walking the same field list
//! that defines the struct (see [`score_block!`]), so a partial emission is
//! unrepresentable. The heavy apex-stage families ([`apex_features`],
//! [`split_product`]) keep their compute here too, leaning on the shared
//! numeric primitives in [`crate::scoring::apex_dsp`].
//!
//! Hand-written exceptions to the macro (they still emit through the same
//! sinks, and their compute still lives in-file):
//! - [`identity::Identity`] — irreducibly mixed-dtype.
//! - array families [`ion_errors::IonErrors`] /
//!   [`relative_intensities::RelativeIntensities`] and the conditional,
//!   features-only [`sequence_counts`] block.
//!
//! The remaining blocks — including the output-only
//! [`result_meta::ResultMeta`] — are macro-generated by [`score_block!`].

use arrow::array::*;
use arrow::datatypes::*;
use std::sync::Arc;

pub mod apex_features;
pub mod counts;
pub mod derived;
pub mod identity;
pub mod intensities;
pub mod ion_errors;
pub mod lazy;
pub mod mobility;
pub mod primary;
pub mod relative_intensities;
pub mod result_meta;
pub mod rt;
pub mod sequence_counts;
pub mod split_product;

// ---------------------------------------------------------------------------
// Trait
// ---------------------------------------------------------------------------

/// A family of scores that projects itself into the two output surfaces.
///
/// `columns` emits the raw stored value at its original dtype (the Parquet
/// projection; schema/name-compatible with the pre-block schema — same column
/// name→dtype→nullability set, though column order may differ). `features` emits the
/// ML projection, which may apply `#[feat(..)]` transforms and fan a single
/// field out to several features.
pub trait ScoreBlock {
    fn columns(&self, out: &mut ColSink);
    fn features(&self, out: &mut FeatSink);
}

// ---------------------------------------------------------------------------
// ColSink — row-oriented Parquet column accumulator
// ---------------------------------------------------------------------------

enum ColData {
    F32(Vec<f32>),
    F64(Vec<f64>),
    U8(Vec<u8>),
    U32(Vec<u32>),
    Bool(Vec<bool>),
    Str(Vec<String>),
}

struct Column {
    name: String,
    nullable: bool,
    data: ColData,
}

/// Accumulates Parquet columns one row at a time.
///
/// Each block's `columns(&self, o)` pushes one value per column, in a fixed
/// order per block. On the first row the columns are created (name + dtype +
/// nullability recorded from the typed method); on later rows the cursor walks
/// the existing columns and appends. Scalars are non-nullable; expanded array
/// columns (`f32_array`) are nullable — this preserves the pre-block
/// column name→dtype→nullability set.
#[derive(Default)]
pub struct ColSink {
    cols: Vec<Column>,
    cursor: usize,
}

impl ColSink {
    pub fn new() -> Self {
        Self::default()
    }

    /// Locate the column at the cursor (creating it with an empty `make()`
    /// buffer on the first row), advance the cursor, and hand back its data
    /// buffer for the caller to append one value to. Centralizes the
    /// first-row-vs-append + order-check logic shared by every typed method.
    fn slot(&mut self, name: &str, nullable: bool, make: impl FnOnce() -> ColData) -> &mut ColData {
        let i = self.cursor;
        if i == self.cols.len() {
            self.cols.push(Column {
                name: name.to_string(),
                nullable,
                data: make(),
            });
        } else {
            debug_assert_eq!(self.cols[i].name, name, "column order mismatch");
        }
        self.cursor += 1;
        &mut self.cols[i].data
    }

    fn push_f32(&mut self, name: &str, nullable: bool, v: f32) {
        match self.slot(name, nullable, || ColData::F32(Vec::new())) {
            ColData::F32(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn f32(&mut self, name: &str, v: f32) {
        self.push_f32(name, false, v);
    }

    pub fn f64(&mut self, name: &str, v: f64) {
        match self.slot(name, false, || ColData::F64(Vec::new())) {
            ColData::F64(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn u8(&mut self, name: &str, v: u8) {
        match self.slot(name, false, || ColData::U8(Vec::new())) {
            ColData::U8(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn u32(&mut self, name: &str, v: u32) {
        match self.slot(name, false, || ColData::U32(Vec::new())) {
            ColData::U32(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn bool(&mut self, name: &str, v: bool) {
        match self.slot(name, false, || ColData::Bool(Vec::new())) {
            ColData::Bool(vals) => vals.push(v),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    pub fn str(&mut self, name: &str, v: &str) {
        match self.slot(name, false, || ColData::Str(Vec::new())) {
            ColData::Str(vals) => vals.push(v.to_string()),
            _ => panic!("column `{name}` dtype mismatch"),
        }
    }

    /// Expand a fixed-size `[f32; N]` into `{prefix}_0 .. {prefix}_{N-1}`
    /// nullable columns (matching the pre-block array-column layout).
    pub fn f32_array<const N: usize>(&mut self, prefix: &str, arr: &[f32; N]) {
        for (i, v) in arr.iter().enumerate() {
            self.push_f32(&format!("{prefix}_{i}"), true, *v);
        }
    }

    /// Finish one row: reset the cursor to the first column.
    pub fn end_row(&mut self) {
        self.cursor = 0;
    }

    /// Drop all accumulated row data, keeping the established schema. Used to
    /// produce a zero-row batch (schema only) from a single sample row.
    pub fn clear_rows(&mut self) {
        for c in &mut self.cols {
            match &mut c.data {
                ColData::F32(v) => v.clear(),
                ColData::F64(v) => v.clear(),
                ColData::U8(v) => v.clear(),
                ColData::U32(v) => v.clear(),
                ColData::Bool(v) => v.clear(),
                ColData::Str(v) => v.clear(),
            }
        }
        self.cursor = 0;
    }

    /// Materialize the accumulated columns into arrow fields + arrays.
    pub fn finish(self) -> (Vec<Field>, Vec<Arc<dyn Array>>) {
        let mut fields = Vec::with_capacity(self.cols.len());
        let mut arrays: Vec<Arc<dyn Array>> = Vec::with_capacity(self.cols.len());
        for c in self.cols {
            let (dtype, arr): (DataType, Arc<dyn Array>) = match c.data {
                ColData::F32(v) => (DataType::Float32, Arc::new(Float32Array::from(v))),
                ColData::F64(v) => (DataType::Float64, Arc::new(Float64Array::from(v))),
                ColData::U8(v) => (DataType::UInt8, Arc::new(UInt8Array::from(v))),
                ColData::U32(v) => (DataType::UInt32, Arc::new(UInt32Array::from(v))),
                ColData::Bool(v) => (DataType::Boolean, Arc::new(BooleanArray::from(v))),
                ColData::Str(v) => (
                    DataType::Utf8,
                    Arc::new(StringArray::from_iter(v.into_iter().map(Some))),
                ),
            };
            fields.push(Field::new(c.name, dtype, c.nullable));
            arrays.push(arr);
        }
        (fields, arrays)
    }
}

// ---------------------------------------------------------------------------
// FeatSink — ML feature accumulator
// ---------------------------------------------------------------------------

/// Accumulates `(name, value)` ML features. The derived feature name is the GBM
/// contract; the transform-suffix convention (`_ln1p`, `_round`, …) is fixed
/// and lives only here + in the `#[feat(..)]` grammar.
#[derive(Default)]
pub struct FeatSink {
    feats: Vec<(&'static str, f64)>,
}

impl FeatSink {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, name: &'static str, v: f64) {
        self.feats.push((name, v));
    }

    /// Push one raw feature per `(name, value)` pair, zipping a const name table
    /// with its array. Shared by the array blocks ([`ion_errors`],
    /// [`relative_intensities`]) so they emit identically.
    pub fn push_slice(&mut self, names: &[&'static str], vals: &[f32]) {
        for (name, v) in names.iter().zip(vals) {
            self.feats.push((name, *v as f64));
        }
    }

    pub fn push_ln1p(&mut self, name: &'static str, x: f64) {
        self.feats.push((name, x.ln_1p()));
    }

    pub fn push_round(&mut self, name: &'static str, x: f64) {
        self.feats.push((name, x.round()));
    }

    /// `(value, name)` pairs, ordered as pushed. Matches the historical
    /// `named_features` element shape (value first).
    pub fn into_named(self) -> Vec<(f64, &'static str)> {
        self.feats.into_iter().map(|(n, v)| (v, n)).collect()
    }
}

// ---------------------------------------------------------------------------
// BlockFixture — fixed sample constants for macro-generated `sample()`
// ---------------------------------------------------------------------------

/// Supplies a fixed constant per field type for a block's generated `sample()`.
/// Sample *values* are arbitrary but finite and non-zero (so ratio-derived
/// features stay finite in tests).
pub trait BlockFixture {
    fn fixture() -> Self;
}

impl BlockFixture for f32 {
    fn fixture() -> Self {
        0.5
    }
}
impl BlockFixture for f64 {
    fn fixture() -> Self {
        0.5
    }
}
impl BlockFixture for u8 {
    fn fixture() -> Self {
        1
    }
}
impl BlockFixture for u32 {
    fn fixture() -> Self {
        1
    }
}
impl BlockFixture for bool {
    fn fixture() -> Self {
        true
    }
}
impl<const N: usize> BlockFixture for [f32; N] {
    fn fixture() -> Self {
        [0.5; N]
    }
}

// ---------------------------------------------------------------------------
// score_block! — the block macro
// ---------------------------------------------------------------------------

/// Generate a scalar score block: the struct, its [`ScoreBlock`] impl
/// (`columns` + `features`), and a `sample()` fixture.
///
/// Adding or renaming a field here is a deliberate two-place edit: the column
/// name is pinned by the parquet schema golden (`scoring::parquet_writer`
/// tests) and the feature name by the feature-name golden (`ml::qvalues`
/// tests). Both goldens fail until updated — that is the contract guard, not an
/// oversight.
///
/// It does NOT generate `compute` — that stays a hand-written inherent fn,
/// because dep signatures vary per block.
///
/// Every field carries exactly one directive attribute controlling its ML
/// (`features`) projection; `columns` always emits the raw value:
/// - `#[feat(t1, t2, ..)]` — one feature per transform (comma = fan-out).
///   Vocabulary: `raw` (no suffix), `ln1p` (`_ln1p`), `round` (`_round`).
/// - `#[raw]` — shorthand for `#[feat(raw)]`.
/// - `#[col_only]` — Parquet column only, no ML feature.
///
/// (The nested-compose grammar and the per-field `feat_with` escape hatch from
/// the design are deferred — unused by the current feature set.)
#[macro_export]
macro_rules! score_block {
    (
        $(#[doc = $doc:literal])*
        pub struct $Name:ident {
            $( #[$($d:tt)*] pub $fname:ident : $fty:tt ),* $(,)?
        }
    ) => {
        $(#[doc = $doc])*
        #[derive(Debug, Clone, Copy, ::serde::Serialize)]
        pub struct $Name {
            $( pub $fname : $fty ),*
        }

        impl $Name {
            /// Fixture with every field a fixed constant (see [`BlockFixture`]).
            pub fn sample() -> Self {
                Self {
                    $( $fname : <$fty as $crate::scoring::blocks::BlockFixture>::fixture() ),*
                }
            }
        }

        impl $crate::scoring::blocks::ScoreBlock for $Name {
            fn columns(&self, o: &mut $crate::scoring::blocks::ColSink) {
                $( $crate::__block_col!(o, self, $fname, $fty); )*
            }
            fn features(&self, o: &mut $crate::scoring::blocks::FeatSink) {
                $( $crate::__block_feat!(o, self, $fname, $($d)*); )*
            }
        }
    };
}

/// Column emission dispatched by field type.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_col {
    ($o:ident, $s:ident, $f:ident, f32) => {
        $o.f32(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, f64) => {
        $o.f64(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, u8) => {
        $o.u8(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, u32) => {
        $o.u32(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, bool) => {
        $o.bool(stringify!($f), $s.$f);
    };
    ($o:ident, $s:ident, $f:ident, str) => {
        $o.str(stringify!($f), &$s.$f);
    };
}

/// Feature emission dispatched by the field's directive.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat {
    ($o:ident, $s:ident, $f:ident, col_only) => {};
    ($o:ident, $s:ident, $f:ident, raw) => { $o.push(stringify!($f), $s.$f as f64); };
    ($o:ident, $s:ident, $f:ident, feat($($t:ident),+ $(,)?)) => {
        $( $crate::__block_feat_one!($o, $s, $f, $t); )+
    };
}

/// A single transform in a `#[feat(..)]` list.
#[macro_export]
#[doc(hidden)]
macro_rules! __block_feat_one {
    ($o:ident, $s:ident, $f:ident, raw) => {
        $o.push(stringify!($f), $s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, ln1p) => {
        $o.push_ln1p(concat!(stringify!($f), "_ln1p"), $s.$f as f64);
    };
    ($o:ident, $s:ident, $f:ident, round) => {
        $o.push_round(concat!(stringify!($f), "_round"), $s.$f as f64);
    };
}
