//! Relative-intensity arrays (per-ion intensity relative to the MS-level
//! total). Built from the secondary-query collector's sorted values.
//!
//! Array family; same shape as [`super::ion_errors`]. Raw-only projection
//! (intensity ratios are already non-negative and monotone, so `abs` is
//! meaningless); column and feature order both run MS2→MS1. Names are
//! `{field}_{i}`, generated by the macro.

use crate::score_block;
use crate::scoring::apex_finding::RelativeIntensityCollector;
use crate::scoring::{
    NUM_MS1_IONS,
    NUM_MS2_IONS,
};

score_block! {
    /// Stage: finalize (per-ion relative intensities from the apex collector).
    pub struct RelativeIntensities {
        #[feat(raw)] pub ms2_intensity_ratios: [f32; NUM_MS2_IONS],
        #[feat(raw)] pub ms1_intensity_ratios: [f32; NUM_MS1_IONS],
    }
}

impl RelativeIntensities {
    pub fn from_collector(r: &RelativeIntensityCollector) -> Self {
        Self {
            ms2_intensity_ratios: r.ms2.get_values_sorted(),
            ms1_intensity_ratios: r.ms1.get_values_sorted(),
        }
    }
}
