//! The PSI-MS `spectrum origin type` subtree: one row per term, with
//! what the term implies.
//!
//! @generated by `scripts/gen_psims_origin_type.py`. Do not edit: run that
//! script instead.
//!
//! Each flag is the transitive closure of `is_a` under a named root,
//! resolved against the ontology at generation time. Membership is derived
//! from the controlled vocabulary rather than hand-picked, and one row per
//! term means the flags cannot disagree with each other.

/// The `data-version` of the ontology this table was taken from.
///
/// `--check` compares this against the published ontology, so most
/// releases will report a difference that leaves the table unchanged.
/// Regenerating then edits only this line.
pub const DATA_VERSION: &str = "4.1.259";

/// One `spectrum origin type` term, and what it implies for a reader.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OriginType {
    /// The PSI-MS accession, without the `MS:` prefix.
    pub accession: u32,
    /// Spectra whose analyte is deliberately wrong, so an FDR can be estimated.
    ///
    /// Closure of `MS:1003192|decoy spectrum`.
    pub decoy: bool,
    /// Spectra whose peak m/z values are calculated rather than measured.
    ///
    /// Closure of `MS:1003074|predicted spectrum`, `MS:1003424|selected fragment theoretical m/z observed intensity spectrum`.
    pub theoretical_mz: bool,
}

/// Every term under `MS:1003072|spectrum origin type`.
///
/// An origin type absent from this table is a term this build has never
/// heard of. The reader reports it rather than guessing, because guessing
/// "target" on an unknown decoy subtype produces an FDR that is wrong
/// instead of absent.
pub const ORIGIN_TYPES: &[OriginType] = &[
    // MS:1003072 spectrum origin type
    OriginType {
        accession: 1_003_072,
        decoy: false,
        theoretical_mz: false,
    },
    // MS:1003073 observed spectrum
    OriginType {
        accession: 1_003_073,
        decoy: false,
        theoretical_mz: false,
    },
    // MS:1003074 predicted spectrum
    OriginType {
        accession: 1_003_074,
        decoy: false,
        theoretical_mz: true,
    },
    // MS:1003075 demultiplexed spectrum
    OriginType {
        accession: 1_003_075,
        decoy: false,
        theoretical_mz: false,
    },
    // MS:1003192 decoy spectrum
    OriginType {
        accession: 1_003_192,
        decoy: true,
        theoretical_mz: false,
    },
    // MS:1003193 shuffle-and-reposition decoy spectrum
    OriginType {
        accession: 1_003_193,
        decoy: true,
        theoretical_mz: false,
    },
    // MS:1003194 precursor shift decoy spectrum
    OriginType {
        accession: 1_003_194,
        decoy: true,
        theoretical_mz: false,
    },
    // MS:1003195 unnatural peptidoform decoy spectrum
    OriginType {
        accession: 1_003_195,
        decoy: true,
        theoretical_mz: false,
    },
    // MS:1003196 unrelated species decoy spectrum
    OriginType {
        accession: 1_003_196,
        decoy: true,
        theoretical_mz: false,
    },
    // MS:1003424 selected fragment theoretical m/z observed intensity spectrum
    OriginType {
        accession: 1_003_424,
        decoy: false,
        theoretical_mz: true,
    },
];

/// The term, if this build knows it.
///
/// A linear scan: the table is ten rows, so an ordering invariant would
/// cost more to state and test than it saves.
pub fn lookup(accession: u32) -> Option<&'static OriginType> {
    ORIGIN_TYPES.iter().find(|term| term.accession == accession)
}
