//! The PSI-MS `spectrum origin type` subtree, as sorted accession lists.
//!
//! @generated by `scripts/gen_psims_origin_type.py`. Do not edit: run that
//! script instead. `--check` compares the version below against the
//! published ontology, so a stale snapshot fails CI rather than going
//! unnoticed.
//!
//! Every list is the transitive closure of `is_a` under a named root,
//! resolved against the ontology at generation time. So membership is
//! derived from the controlled vocabulary rather than hand-picked, and the
//! reader needs only a binary search.

/// The `data-version` of the ontology these lists were taken from.
pub const DATA_VERSION: &str = "4.1.259";

/// Every accession under `MS:1003072|spectrum origin type`, sorted.
///
/// A `spectrum origin type` value outside this list is a term this build
/// has never heard of. The reader reports it rather than guessing, because
/// guessing "target" on an unknown decoy subtype produces an FDR that is
/// wrong instead of absent.
pub const ALL: &[u32] = &[
    1_003_072, 1_003_073, 1_003_074, 1_003_075, 1_003_192, 1_003_193, 1_003_194, 1_003_195,
    1_003_196, 1_003_424,
];

/// Spectra whose analyte is deliberately wrong, so an FDR can be estimated.
///
/// Closure of `MS:1003192|decoy spectrum`.
pub const DECOY: &[u32] = &[1_003_192, 1_003_193, 1_003_194, 1_003_195, 1_003_196];

/// Spectra whose peak m/z values are calculated rather than measured.
///
/// Closure of `MS:1003074|predicted spectrum`, `MS:1003424|selected fragment theoretical m/z observed intensity spectrum`.
pub const THEORETICAL_MZ: &[u32] = &[1_003_074, 1_003_424];

// Terms in this snapshot:
//   MS:1003072  spectrum origin type
//   MS:1003073  observed spectrum
//   MS:1003074  predicted spectrum  [THEORETICAL_MZ]
//   MS:1003075  demultiplexed spectrum
//   MS:1003192  decoy spectrum  [DECOY]
//   MS:1003193  shuffle-and-reposition decoy spectrum  [DECOY]
//   MS:1003194  precursor shift decoy spectrum  [DECOY]
//   MS:1003195  unnatural peptidoform decoy spectrum  [DECOY]
//   MS:1003196  unrelated species decoy spectrum  [DECOY]
//   MS:1003424  selected fragment theoretical m/z observed intensity spectrum  [THEORETICAL_MZ]
