use arrow::array::{
    ArrayRef,
    new_empty_array,
};
use arrow::datatypes::*;
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;
use parquet::basic::Compression;
use parquet::file::metadata::KeyValue;
use parquet::file::properties::WriterProperties;
use std::fs::File;
use std::path::Path;
use std::sync::Arc;
use timsquery::IonAnnot;
use timsquery::models::{
    RowIdx,
    SourceId,
    TargetColumns,
};
use tracing::debug;

use super::blocks::{
    ColSink,
    NameSink,
    SchemaSink,
    ScoreBlock,
};
use super::results::FinalResult;

/// Bumped when a column's meaning or type changes, so a reader can tell a new
/// file from an old one rather than silently misreading it.
///
/// - 2: `library_id` and `decoy_group_id` widened to UInt64. `library_id` was
///   already the caller's id but was truncated to 32 bits; `decoy_group_id`
///   used to be the arena row position and is now an id declared by the input
///   or minted at load.
/// - 3: both became Utf8, because an id keeps the shape its source used and
///   DIA-NN names its precursors with a string (`transition_group_id`). A
///   numeric id is written as its digits.
///
/// `decoy_group_id` equals `library_id` on every row until a library format
/// declares competition groups: no reader parses them today, so a row competes
/// only with its own decoy variants and is its own group. The duplication is
/// expected, not a bug.
pub const RESULTS_FORMAT_VERSION: u32 = 3;

// ---------------------------------------------------------------------------
// Build a RecordBatch from a slice of FinalResult
// ---------------------------------------------------------------------------

/// The ids a reader joins on, resolved from the arena.
///
/// A block rather than two hand-written `o.str` calls in `emit_row` plus two in
/// `FinalResult::column_schema`: that split is exactly the schema/data drift
/// `#[derive(ScoreBlock)]` exists to prevent. A block keeps the pair adjacent,
/// so the two bodies cannot disagree about names, types, or order.
///
/// Hand-written, like `Identity`, because the derive works on owned scalar
/// fields and these are borrowed from the arena.
pub(crate) struct Ids<'a> {
    library_id: SourceId<'a>,
    decoy_group_id: SourceId<'a>,
}

impl<'a> Ids<'a> {
    fn for_row(geom: &'a TargetColumns<IonAnnot>, row: RowIdx) -> Self {
        Self {
            library_id: geom.output_id(row),
            decoy_group_id: geom.decoy_group(row),
        }
    }

    /// A text id goes in borrowed; only a numeric one is rendered.
    fn emit(o: &mut ColSink, name: &str, id: SourceId<'_>) {
        match id {
            SourceId::Text(s) => o.str(name, s),
            SourceId::Numeric(n) => o.str(name, &n.to_string()),
        }
    }
}

impl ScoreBlock for Ids<'_> {
    fn columns(&self, o: &mut ColSink) {
        Self::emit(o, "library_id", self.library_id);
        Self::emit(o, "decoy_group_id", self.decoy_group_id);
    }

    fn column_schema(o: &mut SchemaSink) {
        o.str("library_id");
        o.str("decoy_group_id");
    }

    fn nonlinear_feature_names(_: &mut NameSink) {}
}

/// Emit one result's columns into the sink (all scoring blocks, then the
/// post-model meta block, then the ids resolved from the arena).
///
/// The ids are not on the result: a candidate carries opaque handles so nothing
/// on the scoring path can print one or invent one, and this is the boundary
/// where they become the values a reader joins on.
fn emit_row(r: &FinalResult, geom: &TargetColumns<IonAnnot>, sink: &mut ColSink) {
    r.scoring.columns(sink);
    r.result_meta().columns(sink);
    Ids::for_row(geom, r.scoring.identity.row).columns(sink);
    sink.end_row();
}

/// Zero-row RecordBatch built directly from the block schema — no fake row.
fn empty_batch() -> std::io::Result<RecordBatch> {
    let mut ss = super::blocks::SchemaSink::new();
    FinalResult::column_schema(&mut ss);
    let fields = ss.into_fields();
    let arrays: Vec<ArrayRef> = fields
        .iter()
        .map(|f| new_empty_array(f.data_type()))
        .collect();
    let schema = Arc::new(Schema::new(fields));
    RecordBatch::try_new(schema, arrays)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

/// Build a `RecordBatch` from a slice of `FinalResult`.
///
/// **COMPILE-TIME SAFETY:** each block's `columns()` is generated by walking
/// the same field list that defines the block struct (see
/// `#[derive(ScoreBlock)]` in `timsseek_macros`), so a new field cannot
/// silently skip the Parquet projection — there is no hand-written destructure
/// to fall out of sync.
pub fn build_record_batch(
    results: &[FinalResult],
    geom: &TargetColumns<IonAnnot>,
) -> std::io::Result<RecordBatch> {
    if results.is_empty() {
        return empty_batch();
    }
    let mut sink = ColSink::new();
    for r in results {
        emit_row(r, geom, &mut sink);
    }

    let (fields, arrays) = sink.finish();
    let schema = Arc::new(Schema::new(fields));
    RecordBatch::try_new(schema, arrays)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

// ---------------------------------------------------------------------------
// Buffered Parquet writer
// ---------------------------------------------------------------------------

/// Borrows the arena the results were scored against, because a `FinalResult`
/// carries opaque handles rather than ids and the arena is what turns them back
/// into the values a reader joins on.
pub struct ResultParquetWriter<'a> {
    writer: ArrowWriter<File>,
    buffer: Vec<FinalResult>,
    row_group_size: usize,
    geom: &'a TargetColumns<IonAnnot>,
}

impl<'a> ResultParquetWriter<'a> {
    pub fn new(
        path: impl AsRef<Path>,
        row_group_size: usize,
        parsable_sequences: bool,
        geom: &'a TargetColumns<IonAnnot>,
    ) -> std::io::Result<Self> {
        let file = match File::create_new(path.as_ref()) {
            Ok(f) => f,
            Err(err) => {
                tracing::error!("Failed to create file {:?}: {}", path.as_ref(), err);
                return Err(err);
            }
        };

        // Build schema from a zero-row batch
        let empty_batch = build_record_batch(&[], geom)?;
        let schema = empty_batch.schema();

        let kv = vec![
            KeyValue {
                key: "parsable_sequences".to_string(),
                value: Some(parsable_sequences.to_string()),
            },
            KeyValue {
                key: "results_format_version".to_string(),
                value: Some(RESULTS_FORMAT_VERSION.to_string()),
            },
        ];
        let props = WriterProperties::builder()
            .set_compression(Compression::SNAPPY)
            .set_key_value_metadata(Some(kv))
            .build();

        let writer =
            ArrowWriter::try_new(file, schema, Some(props)).map_err(std::io::Error::other)?;

        Ok(Self {
            writer,
            buffer: Vec::with_capacity(row_group_size),
            row_group_size,
            geom,
        })
    }

    pub fn add(&mut self, result: FinalResult) -> std::io::Result<()> {
        self.buffer.push(result);
        if self.buffer.len() >= self.row_group_size {
            self.flush()?;
        }
        Ok(())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        if self.buffer.is_empty() {
            return Ok(());
        }
        debug!("Flushing {} results to parquet", self.buffer.len());
        let batch = build_record_batch(&self.buffer, self.geom)?;
        self.writer.write(&batch).map_err(std::io::Error::other)?;
        self.buffer.clear();
        Ok(())
    }

    pub fn close(mut self) -> std::io::Result<()> {
        self.flush()?;
        self.writer.close().map_err(std::io::Error::other)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use parquet::file::reader::{
        FileReader,
        SerializedFileReader,
    };
    use std::fs::File;
    use timsquery::models::capabilities::TargetCapabilities;

    /// An unsealed arena holding one row per sequence, for the writer to
    /// resolve ids against. Left unsealed so a caller can attach source ids.
    fn arena_of(seqs: &[&str]) -> TargetColumns<IonAnnot> {
        let mut geom = TargetColumns::with_capabilities(TargetCapabilities::default_diann());
        for seq in seqs {
            geom.push_target(
                900.4,
                2,
                1.0,
                1.0,
                &[(IonAnnot::try_from("y3").unwrap(), 300.0)],
                seq,
                seq,
                &[],
            );
        }
        geom
    }

    fn one_row_arena() -> TargetColumns<IonAnnot> {
        let mut geom = arena_of(&["PEPTIDEK"]);
        geom.seal();
        geom
    }

    /// `FinalResult::sample()` carries a placeholder row, which by design reads
    /// no arena. Point it at a real one before writing.
    fn sample_in(geom: &TargetColumns<IonAnnot>) -> FinalResult {
        let mut r = FinalResult::sample();
        r.scoring.identity.row = geom.rows().next().expect("one row");
        r
    }

    /// Golden byte-compat contract for the Parquet schema.
    ///
    /// The maintained contract: a SUBSET of columns downstream consumers rely on
    /// to join a row and threshold it. Each listed `column_name -> (dtype,
    /// nullable)` must be present and match. Everything else the writer emits
    /// (all the feature/diagnostic columns) is free to change or disappear —
    /// this test does NOT reject extra columns, and column ORDER is not asserted
    /// (downstream reads by name). Add a column here only when you commit to
    /// keeping it stable.
    const GOLDEN_SCHEMA: &[(&str, &str, bool)] = &[
        ("sequence", "Utf8", false),
        ("library_id", "Utf8", false),
        ("decoy_group_id", "Utf8", false),
        ("is_target", "Boolean", false),
        ("precursor_mz", "Float64", false),
        ("precursor_charge", "UInt8", false),
        ("main_score", "Float32", false),
        ("discriminant_score", "Float32", false),
        ("qvalue", "Float32", false),
    ];

    #[test]
    fn schema_first_matches_populated_data_path() {
        // The writer's schema comes from the empty (SchemaSink) batch; real data
        // goes through the ColSink path. They MUST have identical schemas (name,
        // dtype, nullability, ORDER) or the writer rejects populated batches.
        let geom = one_row_arena();
        let empty = build_record_batch(&[], &geom).expect("empty");
        let populated = build_record_batch(&[sample_in(&geom)], &geom).expect("populated");
        assert_eq!(
            empty.schema(),
            populated.schema(),
            "schema-first empty batch must byte-match the ColSink data-path schema"
        );
    }

    /// The ids are not carried on a result any more, so this is what pins that
    /// they still reach the file — and that the row a result points at is the
    /// row whose id gets written.
    #[test]
    fn ids_resolve_from_the_arena_row() {
        use arrow::array::StringArray;

        let mut geom = arena_of(&["PEPTIDEK", "AAAAAAALQAK"]);
        // The names DIA-NN would give these rows, which is the case that must
        // not come back as digits.
        geom.set_source_ids(["PEPTIDEK2", "AAAAAAALQAK2"])
            .expect("two ids for two rows");
        geom.seal();

        let second = geom.rows().nth(1).expect("two rows");
        let mut result = FinalResult::sample();
        result.scoring.identity.row = second;

        let batch = build_record_batch(&[result], &geom).expect("batch");
        let ids = batch
            .column_by_name("library_id")
            .expect("library_id column")
            .as_any()
            .downcast_ref::<StringArray>()
            .expect("library_id is Utf8");
        assert_eq!(ids.value(0), "AAAAAAALQAK2");

        // No declared groups, so the row is its own group and the group id is
        // the id the row reports.
        let groups = batch
            .column_by_name("decoy_group_id")
            .expect("decoy_group_id column")
            .as_any()
            .downcast_ref::<StringArray>()
            .expect("decoy_group_id is Utf8");
        assert_eq!(groups.value(0), "AAAAAAALQAK2");
    }

    #[test]
    fn parquet_schema_contains_maintained_subset() {
        use std::collections::BTreeMap;
        let batch = build_record_batch(&[], &one_row_arena()).expect("schema");
        let got: BTreeMap<String, (String, bool)> = batch
            .schema()
            .fields()
            .iter()
            .map(|f| {
                (
                    f.name().clone(),
                    (format!("{:?}", f.data_type()), f.is_nullable()),
                )
            })
            .collect();

        for (name, dtype, nullable) in GOLDEN_SCHEMA {
            let got_ty = got
                .get(*name)
                .unwrap_or_else(|| panic!("maintained column missing: `{name}`"));
            assert_eq!(
                got_ty,
                &(dtype.to_string(), *nullable),
                "dtype/nullable mismatch for `{name}`"
            );
        }
    }

    #[test]
    fn delta_columns_name_their_ln1p_formulas() {
        let batch = build_record_batch(&[], &one_row_arena()).expect("schema");
        let schema = batch.schema();

        assert!(schema.index_of("delta_group_ln1p_diff").is_ok());
        assert!(schema.index_of("delta_group_ln1p_ratio").is_ok());
        assert!(schema.index_of("delta_group").is_err());
        assert!(schema.index_of("delta_group_ratio").is_err());
    }

    #[test]
    fn parsable_sequences_key_in_parquet_metadata() {
        let tmp = tempfile::NamedTempFile::new().expect("tmpfile");
        let path = tmp.path().to_path_buf();
        // Close the NamedTempFile so ResultParquetWriter can create the file
        // (File::create_new fails if the path already exists on some platforms,
        //  but NamedTempFile holds it open; drop it first).
        drop(tmp);
        {
            let geom = one_row_arena();
            let writer = ResultParquetWriter::new(&path, 1024, true, &geom).expect("create writer");
            writer.close().expect("close");
        }
        let file = File::open(&path).expect("open");
        let reader = SerializedFileReader::new(file).expect("reader");
        let meta = reader.metadata().file_metadata();
        let kv_list = meta.key_value_metadata().expect("kv metadata present");
        let found: Vec<_> = kv_list
            .iter()
            .filter(|k| k.key == "parsable_sequences")
            .collect();
        assert_eq!(
            found.len(),
            1,
            "expected exactly one parsable_sequences key"
        );
        assert_eq!(
            found[0].value.as_deref(),
            Some("true"),
            "parsable_sequences value should be 'true'"
        );
    }
}
