use arrow::datatypes::*;
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;
use parquet::basic::Compression;
use parquet::file::metadata::KeyValue;
use parquet::file::properties::WriterProperties;
use std::fs::File;
use std::path::Path;
use std::sync::Arc;
use tracing::debug;

use super::blocks::{
    ColSink,
    ScoreBlock,
};
use super::results::FinalResult;

// ---------------------------------------------------------------------------
// Build a RecordBatch from a slice of FinalResult
// ---------------------------------------------------------------------------

/// Emit one result's columns into the sink (all scoring blocks, then the
/// post-model meta block).
fn emit_row(r: &FinalResult, sink: &mut ColSink) {
    r.scoring.push_columns(sink);
    r.result_meta().columns(sink);
    sink.end_row();
}

/// Build a `RecordBatch` from a slice of `FinalResult`.
///
/// **COMPILE-TIME SAFETY:** each block's `columns()` is generated by walking
/// the same field list that defines the block struct (see `score_block!`), so
/// a new field cannot silently skip the Parquet projection — there is no
/// hand-written destructure to fall out of sync.
pub fn build_record_batch(results: &[FinalResult]) -> std::io::Result<RecordBatch> {
    let mut sink = ColSink::new();
    if results.is_empty() {
        // Establish the schema from one sample row, then drop the data to
        // produce a zero-row batch (the writer builds its schema this way).
        emit_row(&FinalResult::sample(), &mut sink);
        sink.clear_rows();
    } else {
        for r in results {
            emit_row(r, &mut sink);
        }
    }

    let (fields, arrays) = sink.finish();
    let schema = Arc::new(Schema::new(fields));
    RecordBatch::try_new(schema, arrays)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

// ---------------------------------------------------------------------------
// Buffered Parquet writer
// ---------------------------------------------------------------------------

pub struct ResultParquetWriter {
    writer: ArrowWriter<File>,
    buffer: Vec<FinalResult>,
    row_group_size: usize,
}

impl ResultParquetWriter {
    pub fn new(
        path: impl AsRef<Path>,
        row_group_size: usize,
        parsable_sequences: bool,
    ) -> std::io::Result<Self> {
        let file = match File::create_new(path.as_ref()) {
            Ok(f) => f,
            Err(err) => {
                tracing::error!("Failed to create file {:?}: {}", path.as_ref(), err);
                return Err(err);
            }
        };

        // Build schema from a zero-row batch
        let empty_batch = build_record_batch(&[])?;
        let schema = empty_batch.schema();

        let kv = vec![KeyValue {
            key: "parsable_sequences".to_string(),
            value: Some(parsable_sequences.to_string()),
        }];
        let props = WriterProperties::builder()
            .set_compression(Compression::SNAPPY)
            .set_key_value_metadata(Some(kv))
            .build();

        let writer =
            ArrowWriter::try_new(file, schema, Some(props)).map_err(std::io::Error::other)?;

        Ok(Self {
            writer,
            buffer: Vec::with_capacity(row_group_size),
            row_group_size,
        })
    }

    pub fn add(&mut self, result: FinalResult) -> std::io::Result<()> {
        self.buffer.push(result);
        if self.buffer.len() >= self.row_group_size {
            self.flush()?;
        }
        Ok(())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        if self.buffer.is_empty() {
            return Ok(());
        }
        debug!("Flushing {} results to parquet", self.buffer.len());
        let batch = build_record_batch(&self.buffer)?;
        self.writer.write(&batch).map_err(std::io::Error::other)?;
        self.buffer.clear();
        Ok(())
    }

    pub fn close(mut self) -> std::io::Result<()> {
        self.flush()?;
        self.writer.close().map_err(std::io::Error::other)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use parquet::file::reader::{
        FileReader,
        SerializedFileReader,
    };
    use std::fs::File;

    /// Golden byte-compat contract for the Parquet schema.
    ///
    /// The hard constraint (see score-blocks design): the SET of
    /// `column_name -> (dtype, nullable)` must be identical to the pre-refactor
    /// output. Scalars are non-nullable; expanded `[f32; N]` array columns are
    /// nullable. Column ORDER is intentionally NOT asserted — the design splits
    /// `LazyScores` into apex/secondary blocks, which reorders a few columns,
    /// and downstream reads columns by name. New columns are allowed (this test
    /// updates when the set intentionally grows).
    const GOLDEN_SCHEMA: &[(&str, &str, bool)] = &[
        ("sequence", "Utf8", false),
        ("library_id", "UInt32", false),
        ("decoy_group_id", "UInt32", false),
        ("precursor_mz", "Float64", false),
        ("precursor_charge", "UInt8", false),
        ("precursor_mobility", "Float32", false),
        ("is_target", "Boolean", false),
        ("library_rt", "Float32", false),
        ("calibrated_rt_seconds", "Float32", false),
        ("obs_rt_seconds", "Float32", false),
        ("calibrated_sq_delta_rt", "Float32", false),
        ("obs_mobility", "Float32", false),
        ("delta_ms1_ms2_mobility", "Float32", false),
        ("sq_delta_ms1_ms2_mobility", "Float32", false),
        ("main_score", "Float32", false),
        ("delta_next", "Float32", false),
        ("delta_second_next", "Float32", false),
        ("apex_lazyscore", "Float32", false),
        ("ms2_lazyscore", "Float32", false),
        ("ms2_isotope_lazyscore", "Float32", false),
        ("ms2_isotope_lazyscore_ratio", "Float32", false),
        ("lazyscore_z", "Float32", false),
        ("lazyscore_vs_baseline", "Float32", false),
        ("split_product_score", "Float32", false),
        ("cosine_au", "Float32", false),
        ("scribe_au", "Float32", false),
        ("cosine_cg", "Float32", false),
        ("scribe_cg", "Float32", false),
        ("cosine_weighted_coelution", "Float32", false),
        ("cosine_gradient_consistency", "Float32", false),
        ("scribe_weighted_coelution", "Float32", false),
        ("scribe_gradient_consistency", "Float32", false),
        ("peak_shape", "Float32", false),
        ("ratio_cv", "Float32", false),
        ("centered_apex", "Float32", false),
        ("precursor_coelution", "Float32", false),
        ("fragment_coverage", "Float32", false),
        ("precursor_apex_match", "Float32", false),
        ("xic_quality", "Float32", false),
        ("fragment_apex_agreement", "Float32", false),
        ("isotope_correlation", "Float32", false),
        ("gaussian_correlation", "Float32", false),
        ("per_frag_gaussian_corr", "Float32", false),
        ("rising_cycles", "UInt8", false),
        ("falling_cycles", "UInt8", false),
        ("npeaks", "UInt8", false),
        ("n_scored_fragments", "UInt8", false),
        ("ms2_summed_intensity", "Float32", false),
        ("ms1_summed_intensity", "Float32", false),
        ("delta_group", "Float32", false),
        ("delta_group_ratio", "Float32", false),
        ("discriminant_score", "Float32", false),
        ("qvalue", "Float32", false),
        ("ms2_mz_error_0", "Float32", true),
        ("ms2_mz_error_1", "Float32", true),
        ("ms2_mz_error_2", "Float32", true),
        ("ms2_mz_error_3", "Float32", true),
        ("ms2_mz_error_4", "Float32", true),
        ("ms2_mz_error_5", "Float32", true),
        ("ms2_mz_error_6", "Float32", true),
        ("ms2_mobility_error_0", "Float32", true),
        ("ms2_mobility_error_1", "Float32", true),
        ("ms2_mobility_error_2", "Float32", true),
        ("ms2_mobility_error_3", "Float32", true),
        ("ms2_mobility_error_4", "Float32", true),
        ("ms2_mobility_error_5", "Float32", true),
        ("ms2_mobility_error_6", "Float32", true),
        ("ms1_mz_error_0", "Float32", true),
        ("ms1_mz_error_1", "Float32", true),
        ("ms1_mz_error_2", "Float32", true),
        ("ms1_mobility_error_0", "Float32", true),
        ("ms1_mobility_error_1", "Float32", true),
        ("ms1_mobility_error_2", "Float32", true),
        ("ms2_intensity_ratio_0", "Float32", true),
        ("ms2_intensity_ratio_1", "Float32", true),
        ("ms2_intensity_ratio_2", "Float32", true),
        ("ms2_intensity_ratio_3", "Float32", true),
        ("ms2_intensity_ratio_4", "Float32", true),
        ("ms2_intensity_ratio_5", "Float32", true),
        ("ms2_intensity_ratio_6", "Float32", true),
        ("ms1_intensity_ratio_0", "Float32", true),
        ("ms1_intensity_ratio_1", "Float32", true),
        ("ms1_intensity_ratio_2", "Float32", true),
    ];

    #[test]
    fn parquet_schema_matches_golden_set() {
        use std::collections::BTreeMap;
        let batch = build_record_batch(&[]).expect("schema");
        let got: BTreeMap<String, (String, bool)> = batch
            .schema()
            .fields()
            .iter()
            .map(|f| {
                (
                    f.name().clone(),
                    (format!("{:?}", f.data_type()), f.is_nullable()),
                )
            })
            .collect();
        let want: BTreeMap<String, (String, bool)> = GOLDEN_SCHEMA
            .iter()
            .map(|(n, d, null)| (n.to_string(), (d.to_string(), *null)))
            .collect();

        let missing: Vec<_> = want.keys().filter(|k| !got.contains_key(*k)).collect();
        let extra: Vec<_> = got.keys().filter(|k| !want.contains_key(*k)).collect();
        assert!(missing.is_empty(), "columns missing vs golden: {missing:?}");
        assert!(
            extra.is_empty(),
            "unexpected new columns vs golden: {extra:?}"
        );
        for (name, want_ty) in &want {
            assert_eq!(&got[name], want_ty, "dtype/nullable mismatch for `{name}`");
        }
    }

    #[test]
    fn parsable_sequences_key_in_parquet_metadata() {
        let tmp = tempfile::NamedTempFile::new().expect("tmpfile");
        let path = tmp.path().to_path_buf();
        // Close the NamedTempFile so ResultParquetWriter can create the file
        // (File::create_new fails if the path already exists on some platforms,
        //  but NamedTempFile holds it open; drop it first).
        drop(tmp);
        {
            let writer = ResultParquetWriter::new(&path, 1024, true).expect("create writer");
            writer.close().expect("close");
        }
        let file = File::open(&path).expect("open");
        let reader = SerializedFileReader::new(file).expect("reader");
        let meta = reader.metadata().file_metadata();
        let kv_list = meta.key_value_metadata().expect("kv metadata present");
        let found: Vec<_> = kv_list
            .iter()
            .filter(|k| k.key == "parsable_sequences")
            .collect();
        assert_eq!(
            found.len(),
            1,
            "expected exactly one parsable_sequences key"
        );
        assert_eq!(
            found[0].value.as_deref(),
            Some("true"),
            "parsable_sequences value should be 'true'"
        );
    }
}
