use arrow::array::{
    ArrayRef,
    new_empty_array,
};
use arrow::datatypes::*;
use arrow::record_batch::RecordBatch;
use parquet::arrow::ArrowWriter;
use parquet::basic::Compression;
use parquet::file::metadata::KeyValue;
use parquet::file::properties::WriterProperties;
use std::fs::File;
use std::path::Path;
use std::sync::Arc;
use tracing::debug;

use super::blocks::{
    ColSink,
    ScoreBlock,
};
use super::results::FinalResult;

// ---------------------------------------------------------------------------
// Build a RecordBatch from a slice of FinalResult
// ---------------------------------------------------------------------------

/// Emit one result's columns into the sink (all scoring blocks, then the
/// post-model meta block).
fn emit_row(r: &FinalResult, sink: &mut ColSink) {
    r.scoring.push_columns(sink);
    r.result_meta().columns(sink);
    sink.end_row();
}

/// Zero-row RecordBatch built directly from the block schema — no fake row.
fn empty_batch() -> std::io::Result<RecordBatch> {
    let mut ss = super::blocks::SchemaSink::new();
    FinalResult::column_schema(&mut ss);
    let fields = ss.into_fields();
    let arrays: Vec<ArrayRef> = fields
        .iter()
        .map(|f| new_empty_array(f.data_type()))
        .collect();
    let schema = Arc::new(Schema::new(fields));
    RecordBatch::try_new(schema, arrays)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

/// Build a `RecordBatch` from a slice of `FinalResult`.
///
/// **COMPILE-TIME SAFETY:** each block's `columns()` is generated by walking
/// the same field list that defines the block struct (see
/// `#[derive(ScoreBlock)]` in `timsseek_macros`), so a new field cannot
/// silently skip the Parquet projection — there is no hand-written destructure
/// to fall out of sync.
pub fn build_record_batch(results: &[FinalResult]) -> std::io::Result<RecordBatch> {
    if results.is_empty() {
        return empty_batch();
    }
    let mut sink = ColSink::new();
    for r in results {
        emit_row(r, &mut sink);
    }

    let (fields, arrays) = sink.finish();
    let schema = Arc::new(Schema::new(fields));
    RecordBatch::try_new(schema, arrays)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
}

// ---------------------------------------------------------------------------
// Buffered Parquet writer
// ---------------------------------------------------------------------------

pub struct ResultParquetWriter {
    writer: ArrowWriter<File>,
    buffer: Vec<FinalResult>,
    row_group_size: usize,
}

impl ResultParquetWriter {
    pub fn new(
        path: impl AsRef<Path>,
        row_group_size: usize,
        parsable_sequences: bool,
    ) -> std::io::Result<Self> {
        let file = match File::create_new(path.as_ref()) {
            Ok(f) => f,
            Err(err) => {
                tracing::error!("Failed to create file {:?}: {}", path.as_ref(), err);
                return Err(err);
            }
        };

        // Build schema from a zero-row batch
        let empty_batch = build_record_batch(&[])?;
        let schema = empty_batch.schema();

        let kv = vec![KeyValue {
            key: "parsable_sequences".to_string(),
            value: Some(parsable_sequences.to_string()),
        }];
        let props = WriterProperties::builder()
            .set_compression(Compression::SNAPPY)
            .set_key_value_metadata(Some(kv))
            .build();

        let writer =
            ArrowWriter::try_new(file, schema, Some(props)).map_err(std::io::Error::other)?;

        Ok(Self {
            writer,
            buffer: Vec::with_capacity(row_group_size),
            row_group_size,
        })
    }

    pub fn add(&mut self, result: FinalResult) -> std::io::Result<()> {
        self.buffer.push(result);
        if self.buffer.len() >= self.row_group_size {
            self.flush()?;
        }
        Ok(())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        if self.buffer.is_empty() {
            return Ok(());
        }
        debug!("Flushing {} results to parquet", self.buffer.len());
        let batch = build_record_batch(&self.buffer)?;
        self.writer.write(&batch).map_err(std::io::Error::other)?;
        self.buffer.clear();
        Ok(())
    }

    pub fn close(mut self) -> std::io::Result<()> {
        self.flush()?;
        self.writer.close().map_err(std::io::Error::other)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use parquet::file::reader::{
        FileReader,
        SerializedFileReader,
    };
    use std::fs::File;

    /// Golden byte-compat contract for the Parquet schema.
    ///
    /// The maintained contract: a SUBSET of columns downstream consumers rely on
    /// to join a row and threshold it. Each listed `column_name -> (dtype,
    /// nullable)` must be present and match. Everything else the writer emits
    /// (all the feature/diagnostic columns) is free to change or disappear —
    /// this test does NOT reject extra columns, and column ORDER is not asserted
    /// (downstream reads by name). Add a column here only when you commit to
    /// keeping it stable.
    const GOLDEN_SCHEMA: &[(&str, &str, bool)] = &[
        ("sequence", "Utf8", false),
        ("library_id", "UInt32", false),
        ("decoy_group_id", "UInt32", false),
        ("is_target", "Boolean", false),
        ("precursor_mz", "Float64", false),
        ("precursor_charge", "UInt8", false),
        ("main_score", "Float32", false),
        ("discriminant_score", "Float32", false),
        ("qvalue", "Float32", false),
    ];

    #[test]
    fn schema_first_matches_populated_data_path() {
        // The writer's schema comes from the empty (SchemaSink) batch; real data
        // goes through the ColSink path. They MUST have identical schemas (name,
        // dtype, nullability, ORDER) or the writer rejects populated batches.
        let empty = build_record_batch(&[]).expect("empty");
        let populated = build_record_batch(&[FinalResult::sample()]).expect("populated");
        assert_eq!(
            empty.schema(),
            populated.schema(),
            "schema-first empty batch must byte-match the ColSink data-path schema"
        );
    }

    #[test]
    fn parquet_schema_contains_maintained_subset() {
        use std::collections::BTreeMap;
        let batch = build_record_batch(&[]).expect("schema");
        let got: BTreeMap<String, (String, bool)> = batch
            .schema()
            .fields()
            .iter()
            .map(|f| {
                (
                    f.name().clone(),
                    (format!("{:?}", f.data_type()), f.is_nullable()),
                )
            })
            .collect();

        for (name, dtype, nullable) in GOLDEN_SCHEMA {
            let got_ty = got
                .get(*name)
                .unwrap_or_else(|| panic!("maintained column missing: `{name}`"));
            assert_eq!(
                got_ty,
                &(dtype.to_string(), *nullable),
                "dtype/nullable mismatch for `{name}`"
            );
        }
    }

    #[test]
    fn parsable_sequences_key_in_parquet_metadata() {
        let tmp = tempfile::NamedTempFile::new().expect("tmpfile");
        let path = tmp.path().to_path_buf();
        // Close the NamedTempFile so ResultParquetWriter can create the file
        // (File::create_new fails if the path already exists on some platforms,
        //  but NamedTempFile holds it open; drop it first).
        drop(tmp);
        {
            let writer = ResultParquetWriter::new(&path, 1024, true).expect("create writer");
            writer.close().expect("close");
        }
        let file = File::open(&path).expect("open");
        let reader = SerializedFileReader::new(file).expect("reader");
        let meta = reader.metadata().file_metadata();
        let kv_list = meta.key_value_metadata().expect("kv metadata present");
        let found: Vec<_> = kv_list
            .iter()
            .filter(|k| k.key == "parsable_sequences")
            .collect();
        assert_eq!(
            found.len(),
            1,
            "expected exactly one parsable_sequences key"
        );
        assert_eq!(
            found[0].value.as_deref(),
            Some("true"),
            "parsable_sequences value should be 'true'"
        );
    }
}
